# Generated by Django 4.0.3 on 2022-04-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('discount_percentage', models.IntegerField()),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('gst_percentage', models.IntegerField()),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('added_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('discount_percentage', models.IntegerField()),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('gst_percentage', models.IntegerField()),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('added_on', models.DateField()),
            ],
        ),
    ]
